### ISSUE TITLE
debian系的操作系统，无法安装fcitx-frontend-qt4

### ISSUE THREAD

**Issue by izern** [laomocode/fcitx-sogoupinyin#1]
Hi， 新的发行版移除了qt4相关的包，但搜狗还依赖fcitx-frontend-qt4这个包， 请问有啥办法解决吗

**Comment by ppofp** [comment]
dpkg: 依赖关系问题使得 sogoupinyin 的配置工作不能继续：
 sogoupinyin 依赖于 fcitx-frontend-qt4；然而：
  未安装软件包 fcitx-frontend-qt4。
 sogoupinyin 依赖于 libopencc2 | libopencc1；然而：
  未安装软件包 libopencc2。
  未安装软件包 libopencc1。
 sogoupinyin 依赖于 fcitx-libs | libfcitx-qt0；然而：
  未安装软件包 fcitx-libs。
  未安装软件包 libfcitx-qt0。
 sogoupinyin 依赖于 qml-module-qtquick2；然而：
  未安装软件包 qml-module-qtquick2。

dpkg: 处理软件包 sogoupinyin (--install)时出错：

**Comment by ahkimkoo** [comment]
同问

**Comment by laomocode** [comment]
很抱歉刚刚才看到，这个项目弃坑了，之后有这个项目的后续版本。
